### ISSUE TITLE
Would like to know more about gcc-ia16 bugs

### ISSUE THREAD

**Issue by tkchia** [505e06b2/realmode_kernel#1]
Hello @505e06b2,

I would like to know more about any issues you encountered while using `gcc-ia16`.  I am most concerned with bugs that silently result in incorrect code being generated.  However, reports of other kinds of bugs -- or unpleasant surprises -- would also be useful.

Thank you!

**Comment by tkchia** [comment]
Hello @505e06b2,

I have fixed a bug in `gcc-ia16` in the Intel syntax (`-masm=intel`) mode which you seem to have encountered.  Thank you!

**Comment by 505e06b2** [comment]
Hey @tkchia ,
Sorry about not responding sooner. The only big issue I had run into was this bug you've fixed. Personally, I'm not too well versed in Assembler or GCC internals, though I do know my way around C

I've just updated my packages and I've seen that ia16-elf has been upgraded - this has fixed the peephole2/lds error I was getting

Thank you for your time!

**Comment by 505e06b2** [comment]
If I do encounter any other bugs, would you like them posted to [your repo](https://github.com/tkchia/gcc-ia16/issues) ?

**Comment by tkchia** [comment]
Hello @505e06b2,

> Thank you for your time!

No problem. :)

> If I do encounter any other bugs, would you like them posted to your repo ?

Yes --- please do.  Thanks!
